# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   env:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  #     FORCE_COLOR: 1
  #     EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
  ci:
    name: +ci
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      DATABASE_URL: "${{secrets.DATABASE_URL}}"
    steps:
      - uses: earthly/actions/setup-earthly@v1
      - uses: actions/checkout@v2
      - name: Run +all on Earthly satellite
        run: earthly --push --org jeremyarde --ci --satellite my-satellite +all
      - name: Push docker image to container registry
        run: docker push ghcr.io/jeremyarde/mdp-server:latest
  cd:
    name: +cd
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      DATABASE_URL: "${{secrets.DATABASE_URL}}"
      DOCKERHUB_USERNAME: "${{secrets.DOCKERHUB_USERNAME}}"
      DOCKERHUB_TOKEN: "${{secrets.DOCKERHUB_TOKEN}}"
    steps:
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Earthly version
        run: earthly --version
      - name: Run build
        run: earthly --push +build
        
        # run: earthly --org jeremyarde --ci --satellite my-satellite --push +docker
        # docker push ghcr.io/jeremyarde/mdp-server:latest
    # old stuff below
    # - uses: earthly/actions-setup@v1
    #   with:
    #     version: v0.7.8
    # - uses: actions/checkout@v2
    # - name: Put back the git branch into git (Earthly uses it for tagging)
    #   run: |
    #     branch=""
    #     if [ -n "$GITHUB_HEAD_REF" ]; then
    #       branch="$GITHUB_HEAD_REF"
    #     else
    #       branch="${GITHUB_REF##*/}"
    #     fi
    #     git checkout -b "$branch" || true
    # - name: Docker Login
    #   run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    # - name: Earthly version
    #   run: earthly --version
    # - name: Run build
    #   run: earthly --push +build
