# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]
    # branches: [ ]
  pull_request:
    branches: [main]
    # branches: [ ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   env:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  #     FORCE_COLOR: 1
  #     EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
  ci:
    name: +ci
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
      DATABASE_URL: "${{secrets.DATABASE_URL}}"
      DOCKERHUB_USERNAME: "${{secrets.DOCKERHUB_USERNAME}}"
      DOCKERHUB_TOKEN: "${{secrets.DOCKERHUB_TOKEN}}"
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions/setup-earthly@v1
      - name: Run +all on Earthly satellite
        if: github.ref == 'refs/heads/main'
        run: earthly --org jeremyarde --ci --satellite my-satellite +all
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: Docker Login
        # run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
        run: echo $DOCKERHUB_TOKEN | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - name: Earthly version
        run: earthly --version
      - name: Run build and push
        run: earthly --push +docker

  cd:
    name: +cd
    runs-on: ubuntu-latest
    needs: ci
    env:
      FORCE_COLOR: 1
    steps:
      - name: Send request to trigger deploy
        run: curl https://api.render.com/deploy/srv-cm37666n7f5s73bm0cj0?key=E2VXoYhg5CM
  landingpage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload dist folder
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  # cd:
  #   name: +cd
  #   runs-on: ubuntu-latest
  #   env:
  #     FORCE_COLOR: 1
  #     EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
  #     DATABASE_URL: "${{secrets.DATABASE_URL}}"
  #     DOCKERHUB_USERNAME: "${{secrets.DOCKERHUB_USERNAME}}"
  #     DOCKERHUB_TOKEN: "${{secrets.DOCKERHUB_TOKEN}}"
  #   steps:
  #     - uses: earthly/actions/setup-earthly@v1
  #     - name: Docker Login
  #       run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
  #     - name: Earthly version
  #       run: earthly --version
  #     - name: Run build
  #       run: earthly --push +docker

  # run: earthly --org jeremyarde --ci --satellite my-satellite --push +docker
  # docker push ghcr.io/jeremyarde/mdp-server:latest
  # old stuff below
  # - uses: earthly/actions-setup@v1
  #   with:
  #     version: v0.7.8
  # - uses: actions/checkout@v2
  # - name: Put back the git branch into git (Earthly uses it for tagging)
  #   run: |
  #     branch=""
  #     if [ -n "$GITHUB_HEAD_REF" ]; then
  #       branch="$GITHUB_HEAD_REF"
  #     else
  #       branch="${GITHUB_REF##*/}"
  #     fi
  #     git checkout -b "$branch" || true
  # - name: Docker Login
  #   run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
  # - name: Earthly version
  #   run: earthly --version
  # - name: Run build
  #   run: earthly --push +build
